./gpuusm -k 1 -o omp.csv -d gpu
./gpuusm -k 4 -o omp.csv -d gpu
./gpuusm -k 16 -o omp.csv -d gpu
./gpuusm -k 32 -o omp.csv -d gpu
./gpuusm -k 128 -o omp.csv -d gpu
./gpuusm -k 512 -o omp.csv -d gpu
./gpuusm -m 1 -o omp.csv -d gpu
./gpuusm -m 4 -o omp.csv -d gpu
./gpuusm -m 16 -o omp.csv -d gpu
./gpuusm -m 32 -o omp.csv -d gpu
./gpuusm -m 128 -o omp.csv -d gpu
./gpuusm -m 128 -o omp.csv -d gpu
./gpuusm -m 512 -o omp.csv -d gpu
./gpuusm -m 1024 -o omp.csv -d gpu
./gpuusm -m 2048 -o omp.csv -d gpu
./gpuusm -k 1 -o omp.csv -d cpu
./gpuusm -k 4 -o omp.csv -d cpu
./gpuusm -k 16 -o omp.csv -d cpu
./gpuusm -k 32 -o omp.csv -d cpu
./gpuusm -k 128 -o omp.csv -d cpu
./gpuusm -k 512 -o omp.csv -d cpu
./gpuusm -m 1 -o omp.csv -d cpu
./gpuusm -m 4 -o omp.csv -d cpu
./gpuusm -m 16 -o omp.csv -d cpu
./gpuusm -m 32 -o omp.csv -d cpu
./gpuusm -m 128 -o omp.csv -d cpu
./gpuusm -m 256 -o omp.csv -d cpu
./gpuusm -m 512 -o omp.csv -d cpu
./gpuusm -m 1024 -o omp.csv -d cpu
./gpuusm -m 2048 -o omp.csv -d cpu
